{{- if .Values.tenantOverridesConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cortex.fullname" . }}-tenant-overrides
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  overrides.yaml: {{ tpl (toYaml .Values.tenantOverridesConfig.overridesYaml) . | b64enc}}
{{- end }}
